# Generated by Django 4.1.2 on 2023-10-12 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.TextField(default='')),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(default='abc.jpg', upload_to='Images')),
                ('details', models.TextField(default='')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='MyCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adminapp.product')),
            ],
            options={
                'db_table': 'MyCart',
            },
        ),
    ]
